language: node_js
node_js:
  - "stable"

cache:
  directories:
    - site/node_modules

before_install:
  - cd site

script:
  - npm test
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $BUCKET_NAME
  skip_cleanup: true
  local-dir: build

on:
  branch: master